import fs from 'node:fs/promises';
import path from 'node:path';
import { claudeHome, vOffHome } from './paths.js';

// `v-off setup`: registers Claude Code hooks that forward hook JSON to the
// local v-off server. Format per https://code.claude.com/docs/en/hooks.
//
// Hooks are `type: "command"` with `async: true`: they never block Claude Code,
// never print (stdout of SessionStart/UserPromptSubmit would enter the model's
// context), and show no error notice when v-off is not running.

/** Marker argument that identifies v-off's own hook entries. */
export const HOOK_MARKER = '--v-off-hook';

export const HOOK_EVENTS = [
  'SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PostToolUse', 'PostToolUseFailure',
  'PermissionRequest', 'Notification', 'Stop', 'StopFailure', 'SubagentStop', 'SessionEnd',
] as const;

/** Events whose matcher filters tool names; "*" matches every tool. */
const TOOL_EVENTS = new Set(['PreToolUse', 'PostToolUse', 'PostToolUseFailure', 'PermissionRequest']);

interface HookCommand {
  type: string;
  command?: string;
  async?: boolean;
  [k: string]: unknown;
}
interface MatcherGroup {
  matcher?: string;
  hooks?: HookCommand[];
  [k: string]: unknown;
}
export type ClaudeSettings = { hooks?: Record<string, MatcherGroup[]>; [k: string]: unknown };

export function isOurs(h: HookCommand): boolean {
  return typeof h.command === 'string' && h.command.includes(HOOK_MARKER);
}

export function hookCommand(scriptPath: string): string {
  return `node "${scriptPath}" ${HOOK_MARKER}`;
}

/** Remove v-off hooks; drops matcher groups and events that become empty. Other hooks stay untouched. */
export function removeHooks(settings: ClaudeSettings): { settings: ClaudeSettings; removed: number } {
  const out: ClaudeSettings = structuredClone(settings);
  let removed = 0;
  if (!out.hooks || typeof out.hooks !== 'object') return { settings: out, removed };
  for (const [event, groups] of Object.entries(out.hooks)) {
    if (!Array.isArray(groups)) continue;
    const kept: MatcherGroup[] = [];
    for (const g of groups) {
      if (!g || !Array.isArray(g.hooks)) {
        kept.push(g);
        continue;
      }
      const hooks = g.hooks.filter((h) => {
        const ours = isOurs(h);
        if (ours) removed++;
        return !ours;
      });
      if (hooks.length) kept.push({ ...g, hooks });
      else if (hooks.length === g.hooks.length) kept.push(g);
    }
    if (kept.length) out.hooks[event] = kept;
    else delete out.hooks[event];
  }
  if (Object.keys(out.hooks).length === 0) delete out.hooks;
  return { settings: out, removed };
}

/** Add v-off hooks for every event (replacing earlier v-off entries, so it is idempotent). */
export function addHooks(settings: ClaudeSettings, command: string): ClaudeSettings {
  const { settings: out } = removeHooks(settings);
  out.hooks ??= {};
  for (const event of HOOK_EVENTS) {
    const group: MatcherGroup = { hooks: [{ type: 'command', command, async: true }] };
    if (TOOL_EVENTS.has(event)) group.matcher = '*';
    out.hooks[event] = [...(out.hooks[event] ?? []), group];
  }
  return out;
}

/**
 * The hook script copied to ~/.v-off/hook.mjs. Standalone (no dependencies):
 * reads the hook JSON from stdin, POSTs it to v-off with the capture time and
 * any V_OFF_* variables (e.g. V_OFF_AGENT), and always exits 0 within ~2 s.
 */
export function hookScript(port: number): string {
  return `#!/usr/bin/env node
// v-off hook (generated by \`v-off setup\`). Forwards Claude Code hook JSON to
// the local v-off server. Never prints, never blocks, always exits 0.
import http from 'node:http';

const started = Date.now();
const port = Number(process.env.V_OFF_PORT) || ${port};
const done = () => process.exit(0);
setTimeout(done, 2000);

const chunks = [];
process.stdin.on('data', (c) => chunks.push(c));
process.stdin.on('error', done);
process.stdin.on('end', () => {
  try {
    const body = Buffer.concat(chunks);
    const env = Object.entries(process.env)
      .filter(([k, v]) => k.startsWith('V_OFF_') && !['V_OFF_PORT', 'V_OFF_HOST', 'V_OFF_HOME'].includes(k) && v && /^[\\x20-\\x7e]*$/.test(v) && !v.includes(';'))
      .map(([k, v]) => k + '=' + v)
      .join('; ');
    const headers = { 'content-type': 'application/json', 'content-length': body.length, 'x-v-off-ts': String(started) };
    if (env) headers['x-v-off-env'] = env;
    const req = http.request({ host: '127.0.0.1', port, path: '/api/hook', method: 'POST', headers, timeout: 1500 }, (res) => {
      res.resume();
      res.on('end', done);
    });
    req.on('error', done);
    req.on('timeout', () => { req.destroy(); done(); });
    req.end(body);
  } catch {
    done();
  }
});
`;
}

export interface SetupOptions {
  remove?: boolean;
  dryRun?: boolean;
  port?: number;
  /** Override paths (tests). */
  settingsFile?: string;
  scriptFile?: string;
  now?: Date;
}

export interface SetupResult {
  settingsFile: string;
  scriptFile: string;
  backupFile?: string;
  changed: boolean;
  removed: number;
  added: number;
  settings: ClaudeSettings;
}

function stamp(d: Date): string {
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

async function writeAtomic(file: string, text: string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  await fs.writeFile(tmp, text, 'utf8');
  await fs.rename(tmp, file);
}

/** Install or remove the hooks. Backs up settings.json before writing; never writes on invalid JSON. */
export async function runSetup(opts: SetupOptions = {}): Promise<SetupResult> {
  const settingsFile = opts.settingsFile ?? path.join(claudeHome(), 'settings.json');
  const scriptFile = opts.scriptFile ?? path.join(vOffHome(), 'hook.mjs');
  let raw: string | null = null;
  try {
    raw = await fs.readFile(settingsFile, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  let current: ClaudeSettings = {};
  if (raw !== null && raw.trim()) {
    try {
      const parsed: unknown = JSON.parse(raw);
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('bukan objek JSON');
      current = parsed as ClaudeSettings;
    } catch (err) {
      throw new Error(`${settingsFile} bukan JSON yang valid (${(err as Error).message}). Perbaiki dulu; tidak ada yang diubah.`);
    }
  }

  const { removed } = removeHooks(current);
  const next = opts.remove ? removeHooks(current).settings : addHooks(current, hookCommand(scriptFile));
  const text = JSON.stringify(next, null, 2) + '\n';
  const changed = raw === null ? !opts.remove : text !== raw && JSON.stringify(next) !== JSON.stringify(current);
  const result: SetupResult = {
    settingsFile, scriptFile, changed, removed, added: opts.remove ? 0 : HOOK_EVENTS.length, settings: next,
  };
  if (opts.dryRun) return result;

  if (changed) {
    if (raw !== null) {
      result.backupFile = `${settingsFile}.v-off-backup-${stamp(opts.now ?? new Date())}`;
      await fs.writeFile(result.backupFile, raw, 'utf8');
    }
    await writeAtomic(settingsFile, text);
  }
  if (opts.remove) {
    await fs.rm(scriptFile, { force: true });
  } else {
    await writeAtomic(scriptFile, hookScript(opts.port ?? 4747));
  }
  return result;
}
